[workspace]
members = ["crates/pulsar-app", "crates/pulsar-core", "crates/pulsar-settings"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
rust-version = "1.88"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "2"
toml = "1"
windows = "0.62"
windows-numerics = "0.3"
slint = { version = "1.18", default-features = false, features = ["std", "compat-1-2", "backend-winit", "renderer-software"] }
slint-build = "1.18"
